import type { Exercise } from './types';

/**
 * Dati strutturali del modulo manubri (id, gruppo muscolare, tier, range di
 * carico, controindicazioni). Il contenuto localizzabile vive nelle risorse
 * i18n, chiave `exercises.<id>` — stesso pattern del modulo corpo libero.
 *
 * Vincolo v1: ogni loadRangeKg è sempre compreso tra 5 e 25 kg (per
 * manubrio/per mano, salvo dove l'esercizio usa un solo manubrio). Tutti gli
 * esercizi qui sono accessTier 'free': il secondo set di 16, a pagamento, non
 * è ancora implementato (vedi nota su Exercise.accessTier).
 */
export const dumbbellLibrary: Exercise[] = [
  // --- Petto ---
  {
    id: 'db-chest-floor-press',
    muscleGroup: 'chest',
    secondaryMuscleGroups: ['arms'],
    baseDifficultyTier: 1,
    movementType: 'reps',
    contraindicationTags: ['shoulders', 'wrists'],
    spaceRequirement: '2x2m',
    equipment: 'dumbbell',
    loadRangeKg: { min: 8, max: 20 },
    loadStepKg: 2,
    accessTier: 'free',
  },
  {
    id: 'db-chest-floor-fly',
    muscleGroup: 'chest',
    baseDifficultyTier: 2,
    movementType: 'reps',
    contraindicationTags: ['shoulders'],
    spaceRequirement: '2x2m',
    equipment: 'dumbbell',
    loadRangeKg: { min: 5, max: 12 },
    loadStepKg: 1,
    accessTier: 'free',
  },

  // --- Schiena ---
  {
    id: 'db-back-bent-row',
    muscleGroup: 'back',
    secondaryMuscleGroups: ['arms'],
    baseDifficultyTier: 1,
    movementType: 'reps',
    contraindicationTags: ['back'],
    spaceRequirement: '2x2m',
    equipment: 'dumbbell',
    loadRangeKg: { min: 8, max: 20 },
    loadStepKg: 2,
    accessTier: 'free',
  },
  {
    id: 'db-back-single-row',
    muscleGroup: 'back',
    secondaryMuscleGroups: ['arms'],
    baseDifficultyTier: 2,
    movementType: 'reps',
    contraindicationTags: ['back'],
    spaceRequirement: '2x2m',
    equipment: 'dumbbell',
    loadRangeKg: { min: 8, max: 22 },
    loadStepKg: 2,
    accessTier: 'free',
  },

  // --- Spalle ---
  {
    id: 'db-shoulder-press',
    muscleGroup: 'shoulders',
    secondaryMuscleGroups: ['arms'],
    baseDifficultyTier: 2,
    movementType: 'reps',
    contraindicationTags: ['shoulders', 'wrists'],
    spaceRequirement: '2x2m',
    equipment: 'dumbbell',
    loadRangeKg: { min: 6, max: 16 },
    loadStepKg: 2,
    accessTier: 'free',
  },
  {
    id: 'db-shoulder-lateral-raise',
    muscleGroup: 'shoulders',
    baseDifficultyTier: 1,
    movementType: 'reps',
    contraindicationTags: ['shoulders'],
    spaceRequirement: '2x2m',
    equipment: 'dumbbell',
    loadRangeKg: { min: 5, max: 10 },
    loadStepKg: 1,
    accessTier: 'free',
  },
  {
    id: 'db-shoulder-front-raise',
    muscleGroup: 'shoulders',
    baseDifficultyTier: 1,
    movementType: 'reps',
    contraindicationTags: ['shoulders'],
    spaceRequirement: '2x2m',
    equipment: 'dumbbell',
    loadRangeKg: { min: 5, max: 10 },
    loadStepKg: 1,
    accessTier: 'free',
  },

  // --- Braccia ---
  {
    id: 'db-arms-bicep-curl',
    muscleGroup: 'arms',
    baseDifficultyTier: 1,
    movementType: 'reps',
    contraindicationTags: ['wrists'],
    spaceRequirement: '2x2m',
    equipment: 'dumbbell',
    loadRangeKg: { min: 5, max: 14 },
    loadStepKg: 1,
    accessTier: 'free',
  },
  {
    id: 'db-arms-hammer-curl',
    muscleGroup: 'arms',
    baseDifficultyTier: 1,
    movementType: 'reps',
    contraindicationTags: ['wrists'],
    spaceRequirement: '2x2m',
    equipment: 'dumbbell',
    loadRangeKg: { min: 5, max: 14 },
    loadStepKg: 1,
    accessTier: 'free',
  },
  {
    id: 'db-arms-tricep-extension',
    muscleGroup: 'arms',
    secondaryMuscleGroups: ['shoulders'],
    baseDifficultyTier: 2,
    movementType: 'reps',
    contraindicationTags: ['shoulders', 'wrists'],
    spaceRequirement: '2x2m',
    equipment: 'dumbbell',
    loadRangeKg: { min: 5, max: 12 },
    loadStepKg: 1,
    accessTier: 'free',
  },

  // --- Gambe ---
  {
    id: 'db-legs-goblet-squat',
    muscleGroup: 'legs_glutes',
    secondaryMuscleGroups: ['core'],
    baseDifficultyTier: 1,
    movementType: 'reps',
    contraindicationTags: ['knees'],
    spaceRequirement: '2x2m',
    equipment: 'dumbbell',
    loadRangeKg: { min: 8, max: 25 },
    loadStepKg: 2,
    accessTier: 'free',
  },
  {
    id: 'db-legs-rdl',
    muscleGroup: 'legs_glutes',
    secondaryMuscleGroups: ['back'],
    baseDifficultyTier: 2,
    movementType: 'reps',
    contraindicationTags: ['back', 'knees'],
    spaceRequirement: '2x2m',
    equipment: 'dumbbell',
    loadRangeKg: { min: 8, max: 25 },
    loadStepKg: 2,
    accessTier: 'free',
  },

  // --- Addome ---
  {
    id: 'db-core-russian-twist',
    muscleGroup: 'core',
    secondaryMuscleGroups: ['arms'],
    baseDifficultyTier: 1,
    movementType: 'reps',
    contraindicationTags: ['back'],
    spaceRequirement: '2x2m',
    equipment: 'dumbbell',
    loadRangeKg: { min: 5, max: 10 },
    loadStepKg: 1,
    accessTier: 'free',
  },
  {
    id: 'db-core-suitcase-carry',
    muscleGroup: 'core',
    secondaryMuscleGroups: ['back'],
    baseDifficultyTier: 2,
    movementType: 'hold',
    contraindicationTags: ['back', 'wrists'],
    spaceRequirement: '2x2m',
    equipment: 'dumbbell',
    loadRangeKg: { min: 10, max: 25 },
    loadStepKg: 2,
    accessTier: 'free',
  },

  // --- Full body / composti ---
  {
    id: 'db-fullbody-thruster',
    muscleGroup: 'full_body',
    secondaryMuscleGroups: ['shoulders', 'legs_glutes'],
    baseDifficultyTier: 2,
    movementType: 'reps',
    contraindicationTags: ['shoulders', 'knees'],
    spaceRequirement: '2x2m',
    equipment: 'dumbbell',
    loadRangeKg: { min: 6, max: 16 },
    loadStepKg: 2,
    accessTier: 'free',
  },
  {
    id: 'db-fullbody-renegade-row',
    muscleGroup: 'full_body',
    secondaryMuscleGroups: ['back', 'core'],
    baseDifficultyTier: 3,
    movementType: 'reps',
    contraindicationTags: ['wrists', 'shoulders', 'back'],
    spaceRequirement: '2x2m',
    equipment: 'dumbbell',
    loadRangeKg: { min: 6, max: 14 },
    loadStepKg: 1,
    accessTier: 'free',
  },
];
